name: kiosko
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animated_custom_dropdown: ^3.1.1
  animated_flip_counter: ^0.3.4
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  cupertino_icons: ^1.0.8
  esc_pos_utils_plus: ^2.0.4
  flutter:
    sdk: flutter
  flutter_email_sender: ^7.0.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^4.0.0
  flutter_widget_from_html_core: ^0.16.0
  get: ^4.6.5
  haptic_feedback: ^0.5.1+1
  http: ^0.13.1
  image: ^4.5.4
  internet_connection_checker_plus: ^1.0.1
  intl: ^0.20.2
  liquid_pull_to_refresh: ^3.0.1
  mercadopago_sdk: ^1.3.0
  oktoast: ^3.4.0
  permission_handler: ^12.0.1
  pinput: ^5.0.1
  pos: ^0.3.10
  provider: ^6.1.2
  rive_animated_icon: ^2.0.5
  shared_preferences: ^2.5.2
  sizer: ^3.0.5
  sqflite: ^2.4.2
  thermal_printer_plus: ^1.0.11
  translator: ^0.1.7
  zo_collection_animation: ^0.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
